packages:
  - nab/cli/foo
  - common/server
  - common/nestjs-debate
  - common/debate-web
  - common/cli-shared
  - common/cli
  - common/cli-plugin-debate
  - common/cli-plugin-docs
  - tinybots/cli-plugin-bitbucket

onlyBuiltDependencies: '@nestjs/core,@prisma/client,@prisma/engines,better-sqlite3,prisma'
